### ISSUE TITLE
Allow instructors to add good/bad examples

### ISSUE THREAD

**Issue by lenglund** [ubc/acj-versus#294]
This would be an optional part of setting up an assignment to help increase student confidence in doing comparisons. Instructors would provide a "good" and "bad" answer, which would then appear as the first comparison pair for every student - basically acting as a test run and guaranteeing that first match-up is "easy".

Changes would need to include:
- [x] Updating the database to include the instructor answer pair (#319)
- [x] Updating the comparison workflow (so if the instructor has set this, the instructor pair appears first for every student) (#319)
- [x] Updating the assignment form UI and adding instructions/explanation
- [x] Hooking up the assignment form to the back end (#357)
- [x] Hide these answers from being displayed as instructor answers  (#357)

This ties to #251, so if/when implemented, we may want to discuss further if these answers should be allowed to enter the general student answer pool (i.e., with a checkbox) or left outside the pool with no option to include.

**Comment by andrew-gardener** [comment]
should we structure this to allow more than one instructor comparison example?

**Comment by xcompass** [comment]
I would think so.

**Comment by andrew-gardener** [comment]
Do we want to record the number of comparison examples completed separately or included them in the total # of comparisons completed in the participation screen and the csv report files?

**Comment by xcompass** [comment]
I would say not including them or an option for instructor to set. @lenglund what do you think?

**Comment by lenglund** [comment]
Re: more than one example. This may add unnecessary complexity. At least from the front end, it would be good to limit to one for now. Otherwise, we run into other questions (e.g., is each comparison required by each student or is one selected at random? if each is required, is the order always the same? etc).

From a student POV, the "extra" comparison is just another thing that needs to be completed and therefore should appear in the same way as the regular comparisons. So I think it makes sense to include the extra comparison for instructors in this same context. It is part of the work students need to do to meet the requirements for comparing; as long as it is always the first comparison pair, instructors will know if students did/didn't do it.

I'd suggest we add this to the assignment creation form in the area with the other comparisons. Maybe something like how the self-evaluation works, where an instructor can check a box to include a custom comparison and that progressively reveals fields for entering the answer pair?

**Comment by xcompass** [comment]
That make sense for only one example.

**Comment by lenglund** [comment]
Yes, I think we should limit to one example. The tool is designed for peer feedback; doing instructor examples does not actually result in peer feedback, so limiting this to one (the purpose of which theoretically is to guarantee an "easy" comparison to get students started) makes sense to me.

**Comment by lenglund** [comment]
Answers need to have same options as student answers (using text editor and uploading answers). Consider this in a separate modal? Answers also should be editable until they are compared; then lock them in. (Basically use the same approach as criteria.)

**Comment by lenglund** [comment]
Passing back to @andrew-gardener to hook in back end. I can fine-tune when this is done.

**Comment by lenglund** [comment]
Two issues so far:
- [ ] If I create a new assignment and save practice answers, then go in to edit the answers (all before saving assignment), I can't cancel out of the answer edit (everything seems to do a save, regardless of exit route)
- [ ] If I save an assignment (without practice answers), then go in to edit the assignment and save practice answers, after I save the answers and try to edit them, nothing appears in the input

**Comment by lenglund** [comment]
Assignment's available status is set as true at 12:37pm when the answer start time is tomorrow at 12am. Likely a time zone issue?

**Comment by lenglund** [comment]
Other than issue noted above and fix in PR #364, review is complete.
